### ISSUE TITLE
Font setting doesn't work

### ISSUE THREAD

**Issue by dineshadepu** [valignatev/dotfiles#1]
While setting the font "Hack" I get the follwing error.

`set-face-attribute: Font not available: #<font-spec nil nil Hack nil nil nil nil nil 12.0 nil nil nil ((:name . "Hack 12") (:user-spec . "Hack 12"))>`

I tried some ways, was unable to succedeed.

Any help.

**Comment by valignatev** [comment]
It's because "Hack" font does not installed on your system. You can get it here: https://github.com/source-foundry/Hack#quick-installation

Or try with another font, which you have installed on your computer.

**Comment by valignatev** [comment]
I'll close it. Feel free to ask further if something doesn't work for you.
